server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:localhost:3306/testdb
    username: root
    password: spring1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.review41.domain
    configuration:
      map-underscore-camel-case: true

logging:
  com.review41: debug
  org.mybatis: debug